#!/bin/bash

commit_number=$(git rev-list --count HEAD)
current_version=$(dpkg-parsechangelog -S Version)
new_version="$commit_number-1"

cd mkc/

if [ "$current_version" != "$new_version" ]; then
    dch -v "$new_version" -m "Release automatically generated by install_local.sh script"
else
    echo "Version $new_version already exists in changelog, skipping dch."
fi

cd ..

tar -czvf "mkc_$commit_number.orig.tar.gz" ../../*

set -e

cd mkc/
dpkg-buildpackage -us -uc
cd ..

sudo dpkg -i "mkc_$new_version_x86_64.deb"

echo "Debug package is installed, press [ENTER] to delete it"
read _
echo "Uninstalling debug package..."

sudo dpkg -r mkc

rm -f "mkc_$new_version_x86_64.deb"
