#!/bin/bash

new_pkgver=$(git rev-list --count HEAD)
new_pkgver=$((new_pkgver + 1)) # +1 because the script is executed before commit

set -e

cd ..

# Update Arch PKGBUILD version number
sed -i "s/^pkgver=.*/pkgver=${new_pkgver}/" arch/PKGBUILD

# Update DEBIAN version number
sed -i "s/Version: .*/Version: ${new_pkgver}/" DEBIAN/control


# Maintainer-information (set to the owner of the PPA)
export DEBFULLNAME="Linus Moser"
export DEBEMAIL="megakuul@gmx.ch"

# Update debian version number
dch -v "${new_pkgver}" -D stable -m "Continuous stable release, automatically generated by update_version.sh script"
