name: Build and Upload Debian package

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install packaging tools
        run: |
          sudo apt install -y git dput gnupg

      - name: Import GPG Key
        run: |
          gpg --batch --no-tty --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          gpg --batch --no-tty --import <(echo "${{ secrets.GPG_PUBLIC_KEY }}")

      - name: Build package
        run: |
          cd deb/source
          bash build_source.sh

      - name: Upload package
        run: |
          commit_number=$(git rev-list --count HEAD)
          cd debian/source
          dput ppa:megakuul/mkc "mkc_$commit_number-1_source.changes"

