name: Build and Upload Debian Package

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install debian packaging tools and makedependencies
        run: |
          sudo apt update -y
          sudo apt install -y debhelper clang cmake git devscripts dput gnupg libgtkmm-3.0-dev zlib1g-dev

      - name: Configure GPG
        run: |
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          gpgconf --kill gpg-agent
          gpgconf --launch gpg-agent

      - name: Import GPG key for debian package
        run: |
          gpg --batch --pinentry-mode loopback --no-tty --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          gpg --batch --pinentry-mode loopback --no-tty --import <(echo "${{ secrets.GPG_PUBLIC_KEY }}")

      - name: Build debian package
        run: |
          cd scripts
          bash debian_build_source.sh

      - name: Upload debian package
        run: |
          commit_number=$(git rev-list --count HEAD)
          cd ..
          dput ppa:megakuul/mkc "mkc_$commit_number-1_source.changes"

