name: Build and Upload Debian Package

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test
        run: |
          sudo apt update -y
          sudo apt install gnupg
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import
          echo "Salat" > test.txt
          gpg --batch --yes --local-user megakuulr@gmail.com --clearsign test.txt
          gpg --verify test.txt.asc
          echo "Ok works"
          

      - name: Install debian packaging tools and makedependencies
        run: |
          sudo apt update -y
          sudo apt install -y debhelper clang cmake git devscripts dput gnupg libgtkmm-3.0-dev zlib1g-dev

          
      - name: Import GPG key for debian package
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import

      - name: Configure GPG
        run: |
          # Create directory for gpg configuration
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg

          # Trust the imported key
          echo -e "trust\n5\ny\nquit\n" > gpg-trust-script
          gpg --batch --yes --command-fd 0 --edit-key megakuulr@gmail.com < gpg-trust-script
          
          # Settings to omit the pinentry, because it requires a terminal service (tty)
          echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
          echo "use-agent" > ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          # Setting permissions
          chmod 600 ~/.gnupg/*

          gpg-connect-agent /bye
          gpgconf --reload gpg-agent

          # Display debug information
          gpg --version
          gpg --list-secret-keys

      - name: Build debian package
        run: |
          cd scripts
          bash debian_build_source.sh

      - name: Upload debian package
        run: |
          commit_number=$(git rev-list --count HEAD)
          cd ..
          dput ppa:megakuul/mkc "mkc_$commit_number_source.changes.asc"

