name: Build and Upload Debian Package

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
          

      - name: Install debian packaging tools and makedependencies
        run: |
          sudo apt update -y
          sudo apt install -y debhelper clang cmake git devscripts dput gnupg libgtkmm-3.0-dev zlib1g-dev debsign

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import
          gpg --list-secure-keys

      - name: Build and upload package
        run: |
          cd scripts
          bash debian_build_source.sh megakuulr@gmail.com

      - name: Upload debian package
        run: |
          version=$(dpkg-parsechangelog -S Version)
          cd ..
          ls -l
          dput ppa:megakuul/mkc "mkc_${version}_source.changes"

