name: Build and upload packages

on:
  push:
    branches:
      - main

jobs:
  build-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install debian packaging tools and makedependencies
        run: |
          sudo apt update -y
          sudo apt install -y debhelper clang cmake git devscripts gnupg libgtkmm-3.0-dev

      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import
          gpg --list-secret-keys

      - name: Build ubuntu source packages
        run: |
          # Get version
          version=$(dpkg-parsechangelog -S Version)
          # This will build the source for all specified ubuntu releases
          # Commaseperated list of ubuntu releases must be defined as repository variable
          IFS=',' read -ra RELEASE <<< "${{ vars.UBUNTU_BUILD_RELEASES }}"
          for REL in "${RELEASE[@]}"; do
            dch -v "${version}-${REL}" -D "${REL}" -m "Continuous release, build by CI/CD automation process."
            cd scripts
            bash debian_build_source.sh megakuulr@gmail.com
            cd ..
          done
          
      - name: Build binary debian package
        run: |
          cd scripts
          bash debian_build_binary.sh
      - name: Copy artifacts
        run: |
          # This is a workaround, as upload-artifact does not support relativ paths
          mkdir -p /tmp/artifacts/
          cp ../*.deb ../*.changes ../*.dsc ../*.buildinfo ../*.tar.gz /tmp/artifacts/
          cp -r ../MKC /tmp/artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: package
          path: /tmp/artifacts/

  upload-packages:
    needs: build-packages
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Install dput
        run: |
          sudo apt update -y
          sudo apt install -y dput
          
      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 -d | gpg --batch --import
          gpg --list-secret-keys

      - name: Upload Ubuntu PPA package
        run: |
          cd MKC
          version=$(dpkg-parsechangelog -S Version)
          cd ..
          IFS=',' read -ra RELEASE <<< "${{ env.UBUNTU_BUILD_RELEASES }}"
          for REL in "${RELEASE[@]}"; do
            dput ppa:megakuul/mkc "mkc_${version}-${REL}_source.changes"
          done

      - name: Delete previous 'latest' Debian release package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd MKC
          if gh release view latest --repo megakuul/mkc; then
            gh release delete latest --repo megakuul/mkc
          fi
      - name: Create 'latest' Debian release package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd MKC
          version=$(dpkg-parsechangelog -S Version)
          gh release create latest --title "Latest Release (Version: $version)"

      - name: Upload 'latest' Debian release package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd MKC
          gh release upload latest ../MKC.deb --repo megakuul/mkc

