name: Build and Upload Debian Package

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install debian packaging tools and makedependencies
        run: |
          sudo apt update -y
          sudo apt install -y debhelper clang cmake git devscripts dput gnupg libgtkmm-3.0-dev zlib1g-dev

          
      - name: Import GPG key for debian package
        run: |
          mkdir -p ~/.gnupg
          chmod 700 ~/.gnupg
          
          gpg --batch --import <(echo "${{ secrets.GPG_PRIVATE_KEY }}")
          echo -e "trust\n5\ny\nquit\n" > gpg-trust-script

          # Execute the batch script with GPG
          gpg --batch --yes --command-fd 0 --edit-key megakuulr@gmail.com < gpg-trust-script
          gpg --list-secret-keys

      - name: Configure GPG
        run: |
          # Settings to omit the pinentry, because it requires a terminal service (doesn't work with headless actionrunner)
          
          echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf

          # Display version, in case of problems with the pinentry-skip this can be helpful to debug
          gpg --version
          echo "use-agent" > ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          chmod 600 ~/.gnupg/*


      - name: Build debian package
        run: |
          cd scripts
          bash debian_build_source.sh

      - name: Upload debian package
        run: |
          commit_number=$(git rev-list --count HEAD)
          cd ..
          dput ppa:megakuul/mkc "mkc_$commit_number-1_source.changes"

